[PC-1014] Cleanup of docker stats files

diff --git a/cicd/cleanup-files b/cicd/cleanup-files
--- a/cicd/cleanup-files
+++ b/cicd/cleanup-files
@@ -27,6 +27,12 @@ main() {
         exit 1
     fi
 
+    DOCKER_STATS_FILES="/mnt/shared/docker_stats/*/${STACK_NAME}"
+    if ! OUTPUT=$(ssh deploy@"${DEPLOY_HOST_1}" "sudo rm -f ${DOCKER_STATS_FILES}"); then
+        echo "Failed to remove the docker stats files. Error: ${OUTPUT}"
+        exit 1
+    fi
+
     # Get runtime metrics
     END=$(date +%s); RUNTIME=$((END-START)); HOURS=$((RUNTIME / 3600)); MINUTES=$(( (RUNTIME % 3600) / 60 )); SECONDS=$(( (RUNTIME % 3600) % 60 ));
     echo "${CI_JOB_NAME// /_}_Runtime" $HOURS:$MINUTES:$SECONDS >> metrics.txt
