Test

diff --git a/cicd/deploy-compose-files b/cicd/deploy-compose-files
--- a/cicd/deploy-compose-files
+++ b/cicd/deploy-compose-files
@@ -9,7 +9,7 @@ runhelp() {
     echo "Expected User-defined Variables:"
     echo "  - STACK_NAME: Name of the stack"
     echo "  - SITE_HOSTNAME: URL for the site"
-    echo "  - BASICAUTH_FOR_RESOURCES: Authenication to use for developer resources (i.e. Traefik and Solr)"
+    echo "  - BASICAUTH_FOR_RESOURCES: Authentication to use for developer resources (i.e. Traefik and Solr)"
     echo "  - GITHUB_USER_TOKEN: Used when downloading yq from Github"
     echo "  - DEPLOY_HOST_A: The first host in the cluster"
     echo "  - COMPOSE_PATH: Where to put the docker-compose files on the DEPLOY_HOST_A server"
@@ -211,7 +211,7 @@ apply_prod_changes() {
 
     ## Changes for catalog-prod
     if [ "${STACK_NAME}" == "catalog-prod" ]; then
-        # Set cron/build placement contraint
+        # Set cron/build placement constraint
         ./yq -i ".services.cron.deploy.placement.constraints += [\"node.hostname==${DEPLOY_HOST_A}\"]" docker-compose.catalog.yml;
         ./yq -i ".services.build.deploy.placement.constraints += [\"node.hostname==${DEPLOY_HOST_A}\"]" docker-compose.build.yml;
         # Increase Solr RAM to 4 GB (prod is granted more than non-prod envs)
@@ -278,8 +278,31 @@ restrict_oai() {
     export LINE; ./yq -i '.services.catalog.deploy.labels += env(LINE)' docker-compose.catalog.yml
 }
 
+# set_or_update_docker_secret $SECRET_NAME $SECRET_VALUE
+set_or_update_docker_secret() {
+    SECRET_NAME="$1"
+    SECRET_VALUE="$2"
+    # Check if the secret exists
+    if ssh deploy@"${DEPLOY_HOST_A}" docker secret inspect "${SECRET_NAME}" > /dev/null 2>&1; then
+        echo "Deleting existing secret ${SECRET_NAME}"
+        # TODO does it work in another env (like beta), right now it fails because it's in use by the container
+        if ! ssh deploy@"${DEPLOY_HOST_A}" docker secret rm "${SECRET_NAME}"; then
+            echo 'Can not delete the secret'
+            return
+        fi
+    fi
+    echo "Creating secret ${SECRET_NAME}"
+    printf "%s" "${SECRET_VALUE}" | ssh deploy@"${DEPLOY_HOST_A}" docker secret create "${SECRET_NAME}" -
+}
+
 main() {
-    # Install yq, enbsubst, and sponge
+    set_or_update_docker_secret "MARIADB_MONITORING_PASSWORD" "${MARIADB_MONITORING_PASSWORD}"
+    set_or_update_docker_secret "MARIADB_ROOT_PASSWORD" "${MARIADB_ROOT_PASSWORD}"
+    set_or_update_docker_secret "MARIADB_GALERA_MARIABACKUP_PASSWORD" "${MARIADB_GALERA_MARIABACKUP_PASSWORD}"
+    set_or_update_docker_secret "MARIADB_PASSWORD" "${MARIADB_VUFIND_PASSWORD}"
+    set_or_update_docker_secret "MARIADB_VUFIND_PASSWORD" "${MARIADB_VUFIND_PASSWORD}"
+
+    # Install yq, envsubst, and sponge
     apk add wget gettext moreutils;
     wget --header="Authorization: token ${GITHUB_USER_TOKEN}" \
     "https://github.com/mikefarah/yq/releases/download/v4.26.1/yq_linux_amd64" -O ./yq;
