Fix php-cs-fixer to scan our code; have validate happen before build and for all branches

diff --git a/cicd/validate-vufind-build b/cicd/validate-vufind-build
--- a/cicd/validate-vufind-build
+++ b/cicd/validate-vufind-build
@@ -19,30 +19,46 @@ if [[ -n "$1" || $1 == "-h" || $1 == "--help" || $1 == "help" ]]; then
 fi
 
 main() {
-    echo "Pulling image ${CURR} for validation...";
-    docker pull "${CURR}";
+    echo "Building image"
+    DOCKER_BUILDKIT=1 docker build \
+        --build-arg BUILDKIT_INLINE_CACHE=1 \
+        --build-arg GITHUB_USER_TOKEN="${GITHUB_USER_TOKEN}" \
+        --build-arg VUFIND_VERSION="${VUFIND_VERSION}" \
+        --build-arg SOLR_URL=http://solr:8983/solr \
+        --build-arg SIMPLESAMLPHP_VERSION="${SIMPLESAMLPHP_VERSION}" \
+        --tag validate \
+        --cache-from "${LATEST}" \
+        vufind/;
+
+    EC=$?;
+    if [[ ${EC} -ne 0 ]]; then
+        echo "Failed to build. Sleeping to add delay before potential retry.";
+        sleep 3;
+        exit ${EC};
+    fi;
 
     echo "Running PHP unit tests";
     echo "vendor/bin/phing phpunitfaster -Dphpunit_extra_params=/usr/local/vufind/module/Catalog/tests/unit-tests/";
-    docker run --rm "${CURR}" vendor/bin/phing phpunitfaster -Dphpunit_extra_params=/usr/local/vufind/module/Catalog/tests/unit-tests/;
+    docker run --rm valiidate vendor/bin/phing phpunitfaster -Dphpunit_extra_params=/usr/local/vufind/module/Catalog/tests/unit-tests/;
     EC=$?;
 
     if [[ ${EC} -ne 0 ]]; then
-        echo "One or more unit tests failed. Run the following command to debug";
-        echo "docker run --rm \"${CURR}\" vendor/bin/phing phpunitfaster -Dphpunit_extra_params=/usr/local/vufind/module/Catalog/tests/unit-tests/";
+        echo "One or more unit tests failed. Run the following command in a VuFind container to debug";
+        echo "vendor/bin/phing phpunitfaster -Dphpunit_extra_params=/usr/local/vufind/module/Catalog/tests/unit-tests/";
         exit ${EC};
     fi;
     
     echo "Running code style checks";
     echo "vendor/bin/phing eslint jshint phpcs-console php-cs-fixer-dryrun checkLessToSass phpstan-console";
-    docker run --rm "${CURR}" vendor/bin/phing eslint jshint phpcs-console php-cs-fixer-dryrun checkLessToSass phpstan-console;
+    docker run --rm validate vendor/bin/phing eslint jshint phpcs-console php-cs-fixer-dryrun checkLessToSass phpstan-console;
     EC=$?;
     if [[ ${EC} -ne 0 ]]; then
-        echo "One or more of the style checks failed. Run the following command to debug";
-        echo "docker run --rm \"${CURR}\" vendor/bin/phing eslint jshint phpcs-console php-cs-fixer-dryrun checkLessToSass phpstan-console"
+        echo "One or more of the style checks failed. Run the following command in a VuFind container to debug";
+        echo "vendor/bin/phing eslint jshint phpcs-console php-cs-fixer-dryrun checkLessToSass phpstan-console"
         exit ${EC};
     fi;
 
+    docker image rm validate;
     echo "All validations have passed";
 }
 
